micronaut:
  application:
    name: orangeTalents06CasaDoCodigoKotlin

datasources:
  default:
    url: ${$POSTGRES_URL:`jdbc:postgresql://localhost:5432/db_cdc`}
    username: ${POSTGRES_USERNAME:`postgres`}
    password: ${POSTGRES_PASSWORD:`postgres`}
    driverClassName: org.postgresql.Driver
#    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

# api externa
url-service-cep: https://brasilapi.com.br/api/cep/v1