micronaut:
  application:
    name: orangeTalents06CasaDoCodigoKotlin
  server:
    port: 8080
datasources:
  default:
    url: ${$POSTGRES_URL:`jdbc:postgresql://localhost:5432/db_cdc`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:`postgres`}
    password: ${POSTGRES_PASSWORD:`postgres`}
    schema-generate: CREATE_DROP
    dialect: org.hibernate.dialect.PostgreSQLDialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
# api externa
url-service-cep: https://brasilapi.com.br/api/cep/v1
